/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int LESSTHAN = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int CLASS = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int EXTENDS = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int INT_ARRAY = 17;
  /** RegularExpression Id. */
  int LENGTH = 18;
  /** RegularExpression Id. */
  int MAIN = 19;
  /** RegularExpression Id. */
  int NEW = 20;
  /** RegularExpression Id. */
  int PUBLIC = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int STATIC = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int THIS = 25;
  /** RegularExpression Id. */
  int TRUE = 26;
  /** RegularExpression Id. */
  int VOID = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int STRING_LITERAL = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 31;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 32;
  /** RegularExpression Id. */
  int HEX_LITERAL = 33;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 34;
  /** RegularExpression Id. */
  int OPERATOR = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<\"",
    "\"&&\"",
    "\"boolean\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"int\"",
    "<INT_ARRAY>",
    "\"length\"",
    "\"public static void main\"",
    "\"new\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"String\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "<STRING_LITERAL>",
    "<ID>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"{\"",
    "\"(\"",
    "\"[]\"",
    "\")\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"System.out.println\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\".\"",
    "<OPERATOR>",
  };

}
